---
title: "Script_for_Validation"
author: "Yuxin Wang"
output: 
  html_document: 
    fig_height: 10
    fig_width: 10
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(fig.keep = "high")
```

# library

```{r library}
library(GEOquery)
library(DESeq2)
library(oligo)
library(HsAgilentDesign026652.db)
library(hugene10sttranscriptcluster.db)
library(meta)
library(limma)
library(fgsea)
library(GSVA)
library(org.Hs.eg.db)
library(R.utils)
library(clusterProfiler)
library(ggpubr)
library(ggplotify)
library(patchwork)
library(tidyverse)
```

# validate the HBI in adipocyte dataset

```{r}
# global options
rm(list = ls())
options(stringsAsFactors = FALSE)

# predict
load("./RData/result_BC3_GSE71293.RData")
load("./RData/result_score.RData")

meanNor <- function(x){(x-mean(x))/(max(x)-min(x))}

test <- res_BC3_GSE71293$expMatrix %>% t %>% apply(2, meanNor)  %>% as.data.frame

res <- predict(fit, test, interval = "prediction", level = 0.95)

res <- cbind(res, res_BC3_GSE71293$phenoData) %>% mutate(group = factor(group, levels = c("White", "Beige")))

res.cell <- res

save(res.cell, file = "./RData/result_validation_cell.RData")

```

# validate the HBI in adipose tissue dataset

```{r}
# global options
rm(list = ls())

# predict
load("./RData/result_BT2_GSE122721.RData")
load("./RData/result_score.RData")

meanNor <- function(x){(x-mean(x))/(max(x)-min(x))}

test <- res_BT2_GSE122721$expMatrix %>% t %>% apply(2, meanNor) %>% as.data.frame

res <- predict(fit, test, interval = "prediction", level = 0.95)

res <- cbind(res, res_BT2_GSE122721$phenoData) %>% mutate(group = factor(group, levels = c("WAT", "BAT")))

res.tissue <- res

save(res.tissue, file = "./RData/result_validation_tissue.RData")

```

# GSEA

```{r}
# global options
rm(list = ls())

# load data
load("./RData/result_GTEx_SAT.RData")
load("./RData/result_score.RData")

meanNor <- function(x){(x-mean(x))/(max(x)-min(x))}

matrix <- exprSet[c("DHRS11", "PREX1", "REEP6", "STX11"),] %>% t() %>% apply(2, meanNor) %>% as.data.frame()

res <- predict(fit, matrix, interval = "prediction",level = 0.95) %>% as.data.frame() %>% magrittr::set_colnames("fit")

phenoData$fit <- ifelse(res$fit >= quantile(res$fit)[4], "high", 
                        ifelse(res$fit <= quantile(res$fit)[2], "low", NA))

phenoData <- na.omit(phenoData)

counts <- counts(dds)

counts <- counts[, phenoData$sample]

group <- factor(phenoData[,"fit"])

dds <- DESeqDataSetFromMatrix(counts, 
                              colData = data.frame(group), 
                              design = formula(~-1+group))

dim(dds)
cps <- fpm(dds)
keep1 <- rowSums(cps >= 1) >= ceiling(ncol(dds)*1/3)
dds <- dds[keep1, ]
dim(dds)

dds <- DESeq(dds)

res <- results(dds, contrast = c("group","high","low")) 

dif <- as.data.frame(res) %>% na.omit()

dif$symbol <- gtf$gene_name[match(rownames(dif), gtf$gene_id)]

# prepare gene list
geneList <- dif$log2FoldChange;head(geneList)
StoE <- bitr(dif$symbol, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = "org.Hs.eg.db")
names(geneList) <- as.character(dif$symbol);head(geneList)
geneList <- geneList[names(geneList) %in% StoE$SYMBOL]
names(geneList) <- as.character(StoE$ENTREZID[match(names(geneList), StoE$SYMBOL)]);head(geneList)
geneList <- sort(geneList,decreasing = T);head(geneList)

# download current KEGG list (the database was downloaded on 28 Sep, 2022)
buildGseaList<- function(species) {
  require(clusterProfiler)
  require(tidyverse)
  
  R.utils::setOption("clusterProfiler.download.method",'auto')
  
  keggList <- download_KEGG(species = species)
  
  keggRef <- keggList$KEGGPATHID2NAME
  
  keggPath <- keggList$KEGGPATHID2EXTID
  
  keggPath$from <- keggRef$to[match(keggPath$from, keggRef$from)]
  
  keggPath <- split(keggPath$to, keggPath$from)
  
  keggPath
  
}

keggList <- buildGseaList(species = "hsa")

res.fgsea <- fgsea(pathways = keggList, 
                  stats = geneList,
                  minSize = 5,
                  maxSize = 500)

save(res.fgsea, keggList, geneList, file = "./RData/result_validation_GSEA.RData")

```

# merge

```{r}
# global options
rm(list = ls())

# load data
load("./RData/result_validation_WAT.RData")
load("./RData/result_validation_cell.RData")
load("./RData/result_validation_tissue.RData")
load("./RData/result_validation_GSEA.RData")

p.pre <- ggplot(res.pre, aes(x = fit, y = F72))+
  geom_point(color = "#559575")+
  theme_classic()+
  geom_smooth(method = 'lm', se = F, color = "#6163A3")+
  stat_cor(method = "pearson")+
  labs(x = "HBI", y = "Feature 72")+
  ggtitle("Training cohort")+
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none",
        axis.line.x = element_line(size = 0.5),
        axis.line.y = element_line(size = 0.5),
        axis.ticks.x = element_line(size = 0.5),
        axis.ticks.y = element_line(size = 0.5))

p.val <- ggplot(res.val, aes(x = fit, y = F72))+
  geom_point(color = "#559575")+
  theme_classic()+
  geom_smooth(method = 'lm', se = F, color = "#6163A3")+
  stat_cor(method = "pearson")+
  labs(x = "HBI", y = "Feature 72")+
  ggtitle("Testing cohort")+
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none",
        axis.line.x = element_line(size = 0.5),
        axis.line.y = element_line(size = 0.5),
        axis.ticks.x = element_line(size = 0.5),
        axis.ticks.y = element_line(size = 0.5))

p.cell <- ggplot(res.cell, aes(x = group, y = res, fill = group))+
  geom_boxplot()+
  scale_fill_manual(values = c("#559575", "#6163A3"))+
  theme_classic()+
  labs(x = NULL, y = "HBI")+
  ggtitle("Cell cohort (BC3)")+
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none",
        axis.line.x = element_line(size = 0.5),
        axis.line.y = element_line(size = 0.5),
        axis.ticks.x = element_line(size = 0.5),
        axis.ticks.y = element_line(size = 0.5))+
  stat_compare_means(aes(label = paste0("p=", ..p.format..)), method = "t.test")

p.tissue <- ggplot(res.tissue, aes(x = group, y = res, fill = group))+
  geom_boxplot()+
  scale_fill_manual(values = c("#559575", "#6163A3"))+
  theme_classic()+
  labs(x = NULL, y = "HBI")+
  ggtitle("Tissue cohort (BT2)")+
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none",
        axis.line.x = element_line(size = 0.5),
        axis.line.y = element_line(size = 0.5),
        axis.ticks.x = element_line(size = 0.5),
        axis.ticks.y = element_line(size = 0.5))+
  stat_compare_means(aes(label = paste0("p=", ..p.format..)), method = "t.test")


pathways <- c("Carbon metabolism", "Pyruvate metabolism", "PPAR signaling pathway", "Citrate cycle (TCA cycle)", "Peroxisome", "AMPK signaling pathway", "Fatty acid degradation", "Fatty acid metabolism", "Insulin signaling pathway", "Thermogenesis")

p.gsea <- plotGseaTable(keggList[pathways], geneList, res.fgsea, colwidths = c(4, 3.5, 0.8, 0, 1.1), gseaParam = 0.5, render = F)

p.gsea <- as.ggplot(p.gsea)

pdf(file = "./plot/validation_p1.pdf", width = 11, height = 6)
p.pre+p.val+p.cell+p.tissue+p.gsea+plot_layout(design = 
                                                 "ABEEE
                                                  CDEEE")
dev.off()

```

# meta analysis for HBI

```{r}
# global options
rm(list = ls())

# load data
loads <- function(...){
  file <- list.files(...)
  
  for (i in 1:length(file)) {
    load(file[i], envir = parent.frame(1))
  }
}

loads(path = "./RData/", pattern = "result_B.*", full.names = T)


cohortList <- list(res_BC2_GSE57896_A,
                   res_BC2_GSE57896_B,
                   res_BC3_GSE71293_GW7647,
                   res_BC3_GSE71293_Rosi,
                   res_BC5_GSE115421, 
                   res_BT1_GSE113764, 
                   res_BT2_GSE122721,
                   res_BT3_GSE13070_IR,
                   res_BT3_GSE13070_IS)

load("./RData/result_score.RData")
meanNor <- function(x){(x-mean(x))/(max(x)-min(x))}
datList <- lapply(cohortList, function(x) x$expMatrix %>% t %>% apply(2, meanNor) %>% as.data.frame)
datList <- lapply(datList, function(x) predict(fit, x, interval = "prediction", level = 0.95))
datList <- Reduce(c,datList)

phenoList <- lapply(cohortList, function(x) x$phenoData %>% add_column(cohort = x$gse))
phenoList <- lapply(phenoList, function(x) x[,c("sample", "group", "cohort")])
phenoList <- Reduce(rbind, phenoList)
phenoList$group <- gsub("BAT", "Beige", phenoList$group)
phenoList$group <- gsub("WAT", "White", phenoList$group)

phenoList$hbi <- datList

phenoList$group <- factor(phenoList$group, levels = c("White", "Beige"))

p <- ggplot(phenoList, aes(x = cohort, y = hbi, fill = group))+
  geom_boxplot()+
  theme_classic()+
  labs(x = NULL, y = "HBI", fill = "Group")+
  scale_fill_manual(values = c("#559575", "#6163A3"),labels=c("White", "Brown-like"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

pdf(file = "./plot/meta_HBI_exp.pdf", width = 7, height = 4)
p
dev.off()


dat <- phenoList %>%
      group_by(cohort, group) %>%
      summarise(mean = mean(hbi),
                sd = sd(hbi),
                n = n())
    
dat_e <- dat[dat$group == "Beige",]
colnames(dat_e)[2:ncol(dat_e)] <- paste0(colnames(dat_e)[2:ncol(dat_e)], ".e")
dat_c <- dat[dat$group == "White",]
colnames(dat_c)[2:ncol(dat_c)] <- paste0(colnames(dat_c)[2:ncol(dat_c)], ".c")
dat_s <- merge(dat_e,dat_c, by = "cohort") %>% na.omit()
    
res.hbi <- metacont(n.e, mean.e, sd.e, n.c, mean.c, sd.c,
                     data = dat_s,
                     studlab = cohort,
                     sm = "SMD",
                     fixed = F, random = T, overall = T)

HBI <- c(res.hbi$TE.random, res.hbi$pval.random, nrow(dat_s))
print(HBI)

plotMeta <- function(dat_s, studlab, xlim){
  res <- metacont(n.e, mean.e, sd.e, n.c, mean.c, sd.c,
                     data = dat_s,
                     studlab = cohort,
                     sm = "SMD",
                     fixed = F, random = T, overall = T)

  forest(res,
    test.overall = T,layout = "meta",leftcols = "studlab",
       print.I2 = F, print.tau2 = F, print.pval.Q = F,xlim = xlim,
       smlab = "White     Brown",
       label.test.overall.random = "Overall  ",
       fontsize = 11,colgap.forest.left = "0.5cm",
       leftlabs = paste0("Index ", "(", studlab, ")"))
}

pdf(file = "./plot/meta_HBI.pdf", width = 7, height = 4)
plotMeta(dat_s, studlab = "HBI",xlim=c(-6,6))
dev.off()

```

# comparison analysis

```{r}
# global options
rm(list = ls())

# load data
load("./RData/result_GTEx_SAT.RData")
load("./RData/result_score.RData")

# predict
meanNor <- function(x){(x-mean(x))/(max(x)-min(x))}

matrix <- exprSet[c("DHRS11", "PREX1", "REEP6", "STX11"),] %>% t() %>% apply(2, meanNor) %>% as.data.frame()
res <- predict(fit, matrix, interval = "prediction",level = 0.95) %>% as.data.frame() %>% magrittr::set_colnames("fit") %>% t()


# isolate KEGG term for ssGSEA
buildGseaList <- function(species, selected) {
  require(clusterProfiler)
  require(tidyverse)
  
  R.utils::setOption("clusterProfiler.download.method",'auto')
  keggList <- download_KEGG(species = species)
  
  keggRef <- keggList$KEGGPATHID2NAME %>% filter(to %in% selected)
  
  keggPath <- keggList$KEGGPATHID2EXTID %>% filter(from %in% keggRef$from)
  
  keggPath$from <- keggRef$to[match(keggPath$from, keggRef$from)]
  
  keggPath <- split(keggPath$to, keggPath$from)
  
  keggPath
  
}

geneList <- buildGseaList(species = "hsa", 
                          selected = c("Thermogenesis",
                                       "Fatty acid biosynthesis", 
                                       "Fatty acid degradation",
                                       "PPAR signaling pathway",
                                       "AMPK signaling pathway"))

# rename gene names
IDs <- bitr(rownames(exprSet), fromType = "SYMBOL", toType = "ENTREZID", OrgDb = "org.Hs.eg.db")
entrezMatrix <- exprSet[IDs$SYMBOL,]
rownames(entrezMatrix) <- IDs$ENTREZID

# ssGSEA
beigeSig <- gsva(entrezMatrix, 
                  geneList,
                  method = "ssgsea",
                  kcdf = "Gaussian",
                  abs.ranking = T)  %>% t() %>% scale() %>% as.data.frame()

colnames(beigeSig) <- c("AMPK", "biosynthesis", "degradation", "PPAR", "Thermogenesis")

groupEXP <- function(exprSet, spliteBy, spliteWho, myTitle){
  
  markerEXP <- exprSet[spliteBy, ]
  
  spliteWho$Marker <- ifelse(markerEXP >= mean(markerEXP), "High", "Low")
  
  spliteWho <- gather(spliteWho, process, score, -Marker) %>% 
    mutate(Marker = factor(Marker, levels = c("Low", "High"))) %>% 
    mutate(process = factor(process, levels = c("Thermogenesis", "biosynthesis", "degradation", "PPAR", "AMPK" )))
  
  ggplot(spliteWho, aes(x = process, y = score, fill = Marker))+ 
    geom_boxplot(outlier.size = 0.5)+
    ylim(-4,6)+
    scale_fill_manual(values = c("#559575", "#6163A3"))+
    theme_classic()+
    labs(x = NULL, y = "Z-scored relative indices")+
    scale_x_discrete(labels= c("Thermogenesis", "FA biosynthesis", "FA degradation", "PPAR pathway", "AMPK pathway"))+
    ggtitle(myTitle)+
    theme(plot.title = element_text(hjust = 0.5))+
    stat_compare_means(aes(label = paste0("p=", ..p.format..)), method = "t.test", label.y = 4)+ coord_flip()
}

p1 <- groupEXP(exprSet = res, spliteBy = "fit", spliteWho = beigeSig, myTitle = "HBI classification")
p2 <- groupEXP(exprSet, spliteBy = "UCP1", spliteWho = beigeSig, myTitle = "UCP1 classification")+
  theme(axis.text.y = element_blank())
p3 <- groupEXP(exprSet, spliteBy = "PPARGC1A", spliteWho = beigeSig, myTitle = "PPARGC1A classification")+
  theme(axis.text.y = element_blank())
p4 <- groupEXP(exprSet, spliteBy = "PRDM16", spliteWho = beigeSig, myTitle = "PRDM16 classification")+
  theme(axis.text.y = element_blank())

pdf(file = "./plot/validation_p2.pdf", width = 11, height = 4)
p1+p2+p3+p4+plot_layout(ncol = 4, guides = "collect")
dev.off()

```
