---
title: "Script_for_Obesity"
author: "Yuxin Wang"
output: 
  html_document: 
    fig_height: 10
    fig_width: 10
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(fig.keep = "high")
```

# library

```{r library}
library(limma)
library(GSVA)
library(GSEABase)
library(GEOquery)
library(caret)
library(fgsea)
library(R.utils)
library(clusterProfiler)
library(ggplot2)
library(ggplotify)
library(ggpubr)
library(paletteer)
library(ggrepel)
library(patchwork)
library(tidyverse)
```

# correlation between HBI and biological features in obesity cohort

```{r}
# global options
rm(list = ls())
options(stringsAsFactors = FALSE)

# load data
load("./RData/cohort_GSE135134.RData")

# isolate KEGG term for ssGSEA
buildGseaList <- function(species, selected) {
  require(clusterProfiler)
  require(tidyverse)
  
  R.utils::setOption("clusterProfiler.download.method",'auto')
  keggList <- download_KEGG(species = species)
  
  keggRef <- keggList$KEGGPATHID2NAME %>% filter(to %in% selected)
  
  keggPath <- keggList$KEGGPATHID2EXTID %>% filter(from %in% keggRef$from)
  
  keggPath$from <- keggRef$to[match(keggPath$from, keggRef$from)]
  
  keggPath <- split(keggPath$to, keggPath$from)
  
  keggPath
  
}

geneList <- buildGseaList(species = "hsa", 
                          selected = c("Thermogenesis",
                                       "Fatty acid degradation"))

# rename gene names
IDs <- bitr(rownames(ltpms), fromType = "SYMBOL", toType = "ENTREZID", OrgDb = "org.Hs.eg.db")
entrezMatrix <- ltpms[IDs$SYMBOL,]
rownames(entrezMatrix) <- IDs$ENTREZID

# ssGSEA
beigeSig <- gsva(entrezMatrix, 
                 geneList,
                 method = "ssgsea",
                 kcdf = "Gaussian",
                 abs.ranking = T)  %>% t() %>% scale() %>% as.data.frame()

colnames(beigeSig) <- c("degradation", "Thermogenesis")

# predict HBI
load("./RData/result_score.RData")

meanNor <- function(x){(x-mean(x))/(max(x)-min(x))}

test <- ltpms %>% t() %>% apply(2, meanNor) %>% as.data.frame()
res <- predict(fit, test, interval = "prediction", level = 0.95)
res <- as.data.frame(res)

beigeSig$fit <- res$res
beigeSig$group <- factor(phenoData$group, levels = c("Normal", "Overweight", "Obese"))

save(beigeSig, file = "./RData/result_obesity_HBI.RData")
# load("./RData/result_obesity_HBI.RData")

p.t <- ggplot(beigeSig, aes(x = fit, y = Thermogenesis))+
  geom_point(color = "black")+
  theme_bw()+
  geom_smooth(method = 'lm', se = F, color = "#B44946")+
  stat_cor(method = "pearson")+
  labs(x = "HBI", y = "Thermogenesis")+
  facet_wrap(~group, scales = "free_x")+
  theme(legend.position = "none",
        axis.line.x = element_line(size = 0.3),
        axis.line.y = element_line(size = 0.3),
        axis.ticks.x = element_line(size = 0.3),
        axis.ticks.y = element_line(size = 0.3),
        strip.background = element_rect())

p.d <- ggplot(beigeSig, aes(x = fit, y = degradation))+
  geom_point(color = "black")+
  theme_bw()+
  geom_smooth(method = 'lm', se = F, color = "#B44946")+
  stat_cor(method = "pearson")+
  labs(x = "HBI", y = "FA degradation")+
  facet_wrap(~group, scales = "free_x")+
  theme(legend.position = "none",
        axis.line.x = element_line(size = 0.3),
        axis.line.y = element_line(size = 0.3),
        axis.ticks.x = element_line(size = 0.3),
        axis.ticks.y = element_line(size = 0.3),
        strip.background = element_rect())


pdf(file = "./plot/obesity_p1.pdf", width = 7, height = 5)
p.t/p.d
dev.off()

```

# gene correlation

```{r cor}
# global options
rm(list = ls())

# load data
load("./RData/cohort_GSE135134.RData")
load("./RData/result_obesity_HBI.RData")

# group samples
phenoData$hbi <- beigeSig$fit
phenoData.nor <- phenoData[phenoData$group == "Normal",]
phenoData.ove <- phenoData[phenoData$group == "Overweight",]
phenoData.obe <- phenoData[phenoData$group == "Obese",]

# filter low-expressed genes
dim(ltpms)
keep <- rowSums(ltpms >=1) >= 50
ltpms_clean <- ltpms[keep,]
dim(ltpms_clean)

ltpms.nor <- ltpms_clean[,phenoData.nor$sample]
ltpms.ove <- ltpms_clean[,phenoData.ove$sample]
ltpms.obe <- ltpms_clean[,phenoData.obe$sample]

# gene correlation
cor.gene <- function(dat1, dat2){
  res.cor <- apply(dat2, 1, function(x) cor.test(dat1, x))
  
  res.cor <- sapply(res.cor, function(x) c(x$estimate, x$p.value), simplify = T) %>% t() %>% as.data.frame() %>% magrittr::set_colnames(c("Coefficient", "p"))
  
  res.cor$p <- -log10(res.cor$p)
  res.cor$name <- rownames(res.cor)
  
  res.cor
}

res.nor <- cor.gene(dat1 = phenoData.nor$hbi, dat2 = ltpms.nor) %>% na.omit()
res.ove <- cor.gene(dat1 = phenoData.ove$hbi, dat2 = ltpms.ove) %>% na.omit()
res.obe <- cor.gene(dat1 = phenoData.obe$hbi, dat2 = ltpms.obe) %>% na.omit()

pnor <- ggplot(res.nor, aes(x = Coefficient, y = p, color = Coefficient))+
  geom_point()+
  scale_color_paletteer_c("ggthemes::Classic Red-Blue", direction = -1, limits = c(-1, 1))+
  labs(x = " ",y = "-log10(P Value)", title = "Gene correlations (Normal)")+
  geom_label_repel( 
    data = res.nor[res.nor$name %in% c("FASN", "COX5A", "COX6A1", "CPT2", "ELOVL3", "PPARG"),], 
    aes(label = name)
  )+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))

pove <- ggplot(res.ove, aes(x = Coefficient, y = p, color = Coefficient))+
  geom_point()+
  scale_color_paletteer_c("ggthemes::Classic Red-Blue", direction = -1, limits = c(-1, 1))+
  labs(x = " ",y = "-log10(P Value)", title = "Gene correlations (Overweight)")+
  geom_label_repel( 
    data = res.ove[res.ove$name %in% c("ELOVL3", "COX5A", "FASN", "COX7B", "PPARG", "CPT"),], 
    aes(label = name)
  )+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))

pobe <- ggplot(res.obe, aes(x = Coefficient, y = p, color = Coefficient))+
  geom_point()+
  scale_color_paletteer_c("ggthemes::Classic Red-Blue", direction = -1, limits = c(-1, 1))+
  labs(x = " ",y = "-log10(P Value)", title = "Gene correlations (Obese)")+
  geom_label_repel( 
    data = res.obe[res.obe$name %in% c("FASN", "COX5A", "COX6A1", "CPT2", "ELOVL3"),], 
    aes(label = name)
  )+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))

pdf(file = "./plot/obesity_p2.pdf", width = 11, height = 3.5)
pnor+pove+pobe+plot_layout(guides = "collect")
dev.off()


goList.nor <- res.nor %>% arrange(Coefficient) %>% tail(1000) %>% magrittr::use_series("name")
goList.ove <- res.ove %>% arrange(Coefficient) %>% tail(1000) %>% magrittr::use_series("name")
goList.obe <- res.obe %>% arrange(Coefficient) %>% tail(1000) %>% magrittr::use_series("name")

go.nor <- enrichGO(goList.nor, 
               OrgDb = "org.Hs.eg.db", 
               ont = 'BP',
               pAdjustMethod = 'BH',
               pvalueCutoff = 0.05, 
               qvalueCutoff = 0.99,
               keyType = "SYMBOL")

go.ove <- enrichGO(goList.ove, 
               OrgDb = "org.Hs.eg.db", 
               ont = 'BP',
               pAdjustMethod = 'BH',
               pvalueCutoff = 0.05, 
               qvalueCutoff = 0.99,
               keyType = "SYMBOL")

go.obe <- enrichGO(goList.obe, 
               OrgDb = "org.Hs.eg.db", 
               ont = 'BP',
               pAdjustMethod = 'BH',
               pvalueCutoff = 0.05, 
               qvalueCutoff = 0.99,
               keyType = "SYMBOL")

categorys <- c("fatty acid oxidation", "lipid oxidation", "cold-induced thermogenesis", "response to insulin")
p1 <- barplot(go.nor, title = "Normal", showCategory = categorys)+
  scale_fill_paletteer_c("ggthemes::Classic Red-Blue", direction = -1, trans = "reverse")+
  theme(plot.title = element_text(hjust = 0.5))

categorys <- c("fatty acid oxidation", "fatty acid catabolic process","cellular response to insulin stimulus", "cellular respiration")
p2 <- barplot(go.ove, title = "Overweight", showCategory = categorys)+
  scale_fill_paletteer_c("ggthemes::Classic Red-Blue", direction = -1, trans = "reverse")+
  theme(plot.title = element_text(hjust = 0.5))

categorys <- c("cellular respiration", "fatty acid catabolic process", "lipid oxidation", "fatty acid biosynthetic process")
p3 <- barplot(go.obe, title = "Obese", showCategory = categorys)+
  scale_fill_paletteer_c("ggthemes::Classic Red-Blue", direction = -1, trans = "reverse")+
  theme(plot.title = element_text(hjust = 0.5))

pdf(file = "./plot/obesity_p3.pdf", width = 6, height = 8)
p1+p2+p3+plot_layout(ncol = 1)
dev.off()

```

# download matsuda index in GSE70353

```{r matsuda}
# global options
rm(list = ls())

# download data
Sys.setenv(VROOM_CONNECTION_SIZE = 13107200)
eset <- getGEO("GSE70353", destdir="./rawData/GSE70353", AnnotGPL = F, getGPL = F)
eset <- eset[[1]]
phenoData <- pData(eset)

phenoData <- data.frame(sample = phenoData$title,
                        matsuda = phenoData$characteristics_ch1.10)
phenoData$matsuda <- gsub(".*: ", "", phenoData$matsuda) %>% as.numeric()
phenoData <- na.omit(phenoData)

phenoData$sample <- paste0("X", phenoData$sample)
phenoData.matsuda <- phenoData

save(phenoData.matsuda, file = "./RData/result_matsuda.RData")

```

# matsuda analysis

```{r}
# global options
rm(list = ls())

# load data
load("./RData/cohort_GSE135134.RData")
load("./RData/result_obesity_HBI.RData")
load("./RData/result_matsuda.RData")

# merge data
phenoData <- phenoData[phenoData$sample %in% phenoData.matsuda$sample,]
phenoData$matsuda <- phenoData.matsuda$matsuda[match(phenoData$sample, phenoData.matsuda$sample)]
phenoData$group3 <- ifelse(phenoData$matsuda >= 4.3, "IS", "IR")

ltpms <- ltpms[,phenoData$sample]

# HBI classification
phenoData$hbi <- beigeSig$fit[match(phenoData$sample, rownames(beigeSig))]
phenoData$degradation <- beigeSig$degradation[match(phenoData$sample, rownames(beigeSig))]
phenoData$Thermogenesis <- beigeSig$Thermogenesis[match(phenoData$sample, rownames(beigeSig))]

phenoData$group2 <- ifelse(phenoData$hbi > 0, "high", "low")
phenoData$group2 <- factor(phenoData$group2, levels = c("low", "high"))

phenoData <- phenoData[phenoData$group3 == "IR",]

dat <- subset(phenoData, select = c("hbi", "degradation","Thermogenesis")) %>%
  gather(group, dat, -hbi)
dat$group <- gsub("degradation", "FA degradation", dat$group)

p1 <- ggplot(dat, aes(x = hbi, y = dat))+
  geom_point(color = "black")+
  theme_bw()+
  geom_smooth(method = 'lm', se = F, color = "#B44946")+
  stat_cor(method = "pearson")+
  labs(x = "HBI", y = "ssGSEA score")+
  facet_wrap(~group, scales = "free_y")+
  theme(axis.line.x = element_line(size = 0.3),
        axis.line.y = element_line(size = 0.3),
        axis.ticks.x = element_line(size = 0.3),
        axis.ticks.y = element_line(size = 0.3),
        strip.background = element_rect())

pdf(file = "./plot/obesity_p4.pdf", width = 5, height = 2.5)
p1
dev.off()

# gene correlation
cor.gene <- function(dat1, dat2){
  res.cor <- apply(dat2, 1, function(x) cor.test(dat1, x))
  
  res.cor <- sapply(res.cor, function(x) c(x$estimate, x$p.value), simplify = T) %>% t() %>% as.data.frame() %>% magrittr::set_colnames(c("Coefficient", "p"))
  
  res.cor$p <- -log10(res.cor$p)
  res.cor$name <- rownames(res.cor)
  
  res.cor
}

ltpms <- ltpms[,phenoData$sample]
res.cor <- cor.gene(dat1 = phenoData$hbi, dat2 = ltpms) %>% na.omit()

p2 <- ggplot(res.cor, aes(x = Coefficient, y = p, color = Coefficient))+
  geom_point()+
  scale_color_paletteer_c("ggthemes::Classic Red-Blue", direction = -1, limits = c(-1, 1))+
  labs(x = " ",y = "-log10(P Value)", title = "Gene correlations (IR)")+
  geom_label_repel( 
    data = res.cor[res.cor$name %in% c("COX5A", "COX7C","FASN", "PPARG", "ACSL1", "ACSL3"),], 
    aes(label = name)
  )+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))

pdf(file = "./plot/obesity_p5.pdf", width = 5, height = 2.5)
p2
dev.off()

goList.cor <- res.cor %>% arrange(Coefficient) %>% tail(1000) %>% magrittr::use_series("name")

go.cor <- enrichGO(goList.cor, 
               OrgDb = "org.Hs.eg.db", 
               ont = 'BP',
               pAdjustMethod = 'BH',
               pvalueCutoff = 0.05, 
               qvalueCutoff = 0.99,
               keyType = "SYMBOL")

categorys <- c("cellular respiration", "oxidative phosphorylation", "fatty acid metabolic process", "fatty acid catabolic process", "lipid catabolic process", "cellular lipid catabolic process", "lipid oxidation", "fatty acid oxidation", "fatty acid beta-oxidation", "fatty acid biosynthetic process", "positive regulation of cold-induced thermogenesis", "cold-induced thermogenesis")

pdf(file = "./plot/obesity_p6.pdf", width = 8, height = 5)
dotplot(go.cor, title = "Insulin resistance", showCategory = categorys, label_format = 99999)+
  scale_fill_paletteer_c("ggthemes::Classic Red-Blue", direction = -1, trans = "reverse")+
  theme(plot.title = element_text(hjust = 0.5))
dev.off()

```

