---
title: "Script_for_absHBI"
author: "Yuxin Wang"
output: 
  html_document: 
    fig_height: 10
    fig_width: 10
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(fig.keep = "high")
```

# library

```{r library}
library(caret)
library(caretEnsemble)
library(ggplot2)
library(ggpubr)
library(paletteer)
library(ggrepel)
library(patchwork)
library(DESeq2)
library(limma)
library(clusterProfiler)
library(FactoMineR)
library(factoextra)
library(tidyverse)
```

```{r}
# global options
rm(list = ls())
options(stringsAsFactors = FALSE)

# load data
load("./RData/result_GTEx_SAT.RData")
load("./RData/result_GTEx_autoencoders.RData")

absRank <- function(exprSet, background){
  background <- c(background, "DHRS11", "REEP6", "STX11") %>% unique()
  exprSet <- exprSet[rownames(exprSet) %in% background,]
  size <- nrow(exprSet)
  locList <- c()
  pb <- txtProgressBar(style=3)
  for (i in 1:ncol(exprSet)) {
    exprSelect <- exprSet[,i] %>% 
      as.data.frame() %>% 
      magrittr::set_colnames("sample") %>% 
      arrange(sample) %>% 
      rownames_to_column("symbol")
    
    geneloc <- c(
    grep("DHRS11", exprSelect$symbol),
    grep("REEP6", exprSelect$symbol),
    grep("STX11", exprSelect$symbol))
    
    geneloc <- (geneloc/size)*100
    
    locList <- rbind(locList, geneloc) %>% as.data.frame() %>% remove_rownames()
    setTxtProgressBar(pb, i/ncol(exprSet))
  }
  rownames(locList) <- colnames(exprSet)
  colnames(locList) <- c("DHRS11", "REEP6", "STX11")
  close(pb)
  locList
}

rankList <- absRank(exprSet, background = rownames(exprSet))

plotCor <- function(dat.1, dat.2, names, color){
  dat <- cbind(dat.1,dat.2) %>% as.data.frame()
  colnames(dat) <- c("dat.1", "dat.2")
  ggplot(dat, aes(x = dat.1, y = dat.2))+
  geom_point(color = color, alpha = 0.5)+
  theme_classic()+
  geom_smooth(method = 'lm', se = F, color = "black")+
  stat_cor(method = "pearson")+
  labs(x = names[1], y = names[2])
}

feature <- as.data.frame(feature)
p1 <- plotCor(dat.1 = feature$F72, dat.2 = rankList$DHRS11, names = c("Feature 72", "DHRS11"), color = "#DB802D")
p2 <- plotCor(dat.1 = feature$F72, dat.2 = rankList$REEP6, names = c("Feature 72", "REEP6"), color = "#559575")
p3 <- plotCor(dat.1 = feature$F72, dat.2 = rankList$STX11, names = c("Feature 72", "STX11"), color = "#0095C4")

pdf(file = "./plot/abs_cor.pdf", width = 7, height = 5)
p1+p2+p3+plot_layout(ncol = 2)
dev.off()

```

# select background genes

```{r}
# global options
rm(list = ls())
options(stringsAsFactors = FALSE)

# load data
load("./RData/result_GTEx_SAT.RData")
load("./RData/result_GTEx_autoencoders.RData")

feature <- as.data.frame(feature) %>% arrange(F72)

phenoData <- phenoData[match(rownames(feature), phenoData$sample),]

exprSet <- exprSet[,rownames(feature)]

cor.gene <- function(dat1, dat2){
  res.cor <- apply(dat2, 1, function(x) cor.test(dat1, x))
  
  res.cor <- sapply(res.cor, function(x) c(x$estimate, x$p.value), simplify = T) %>% t() %>% as.data.frame() %>% magrittr::set_colnames(c("Coefficient", "p"))
  
  res.cor$p <- res.cor$p
  res.cor$name <- rownames(res.cor)
  
  res.cor
}

res.cor1 <- cor.gene(dat1 = exprSet["DHRS11",], dat2 = exprSet) %>% na.omit()
bg1 <- res.cor1$name[res.cor1$Coefficient <= -0.35 & res.cor1$p <= 0.05]

res.cor2 <- cor.gene(dat1 = exprSet["REEP6",], dat2 = exprSet) %>% na.omit()
bg2 <- res.cor2$name[res.cor2$Coefficient <= -0.42 & res.cor2$p <= 0.05]

res.cor3 <- cor.gene(dat1 = exprSet["STX11",], dat2 = exprSet) %>% na.omit()
bg3 <- res.cor3$name[res.cor3$Coefficient <= -0.5 & res.cor3$p <= 0.05]


whiteList <- head(feature,100) %>% rownames()
beigeList <- tail(feature,100) %>% rownames()

whiteSet <- exprSet[,whiteList]
beigeSet <- exprSet[,beigeList]

genePre <- list()
for (i in c("DHRS11", "REEP6", "STX11")) {
  a <- apply(whiteSet, 2, function(x) rownames(whiteSet)[x > x[i]]) %>% Reduce(c,.) %>% table()
  a <- names(a)[a >= 30]
  
  b <- apply(beigeSet, 2, function(x) rownames(beigeSet)[x < x[i]]) %>% Reduce(c,.) %>% table()
  b <- names(b)[b >= 30]
  
  genePre[[i]] <- intersect(a,b) %>% unique()
  rm(i,a,b)
}

genePre[["DHRS11"]] <- intersect(genePre[["DHRS11"]],bg1)
genePre[["REEP6"]] <- intersect(genePre[["REEP6"]],bg2)
genePre[["STX11"]] <- intersect(genePre[["STX11"]],bg3)


save(genePre, file = "./RData/result_abs_background.RData")

```

# gene ranking

```{r}
absHBindex <- function(exprSet, background){
  locAll <- c()
  for (i in names(background)) {
    bg <- c(background[[i]], i) %>% unique()
    exp <- exprSet[rownames(exprSet) %in% bg,]
    size <- nrow(exp)
    locList <- c()

    for (j in 1:ncol(exp)) {
    exprSelect <- exp[,j] %>% 
      as.data.frame() %>% 
      magrittr::set_colnames("sample") %>% 
      arrange(sample) %>% 
      rownames_to_column("symbol")
    
    geneloc <- grep(i, exprSelect$symbol)
    geneloc <- (geneloc/size)
    locList <- c(locList, geneloc)
    
    }
    locAll <- cbind(locAll, locList)%>% as.data.frame() %>% remove_rownames()
  }
  
  rownames(locAll) <- colnames(exprSet)
  colnames(locAll) <- names(background)

  locAll
}

absHBI <- absHBindex(exprSet, background = genePre)

```


```{r}
# absolute HBindex
abs <- absHBI %>% 
  as.data.frame() %>%
  rownames_to_column("sample") %>% 
  gather(Signature, exp, -sample) %>% 
  mutate(sample = factor(sample, levels = phenoData$sample))

p2 <- ggplot(abs, aes(x = sample, y = exp, group = Signature, color = Signature))+
  geom_point(size = 0.7)+
  scale_color_manual(values = c("#DB802D", "#559575", "#0095C4"))+
  labs(x = "Sample", y = "Normalized RER")+
  theme_classic()+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())+facet_wrap(~Signature, ncol =  2)

pdf(file = "./plot/abs_RER.pdf", width = 6, height = 5)
p2
dev.off()

```

# machine learning

```{r}
meanNor <- function(x){(x-mean(x))/(max(x)-min(x))}

dat <- absHBI %>% cbind(feature) %>%
  subset(select = c("F72", "DHRS11", "REEP6", "STX11")) %>% 
  as.data.frame() %>%
  mutate(F72 = meanNor(F72))

set.seed(123)
index <- createDataPartition(dat$F72, times = 1, p = 0.7, list = F) 

dat.train <- dat[index,]
dim(dat.train)

dat.test <- dat[-index,]
dim(dat.test)

control <- trainControl(method = "cv", 
                        number = 10,
                        index = createResample(dat.train$F72, 10),
                        savePredictions = "final",
                        classProbs = FALSE)

set.seed(2222)
models <- caretList(
  F72 ~ ., 
  data = dat.train,
  trControl = control,
  metric = "Rsquared",
  methodList = c("enet", "rf", "neuralnet", "brnn")
)

models

modelCor(resamples(models))

modelss <- models

# model selection
modelss$enet <- NULL

stack <- caretStack(modelss, 
                    method = "glm",
                    metric = "Rsquared",
                    trControl=trainControl(method="cv",
                                           number=10,
                                           index = createResample(dat.train$F72, 10),
                                           savePredictions = "final",
                                           classProbs = FALSE))


summary(stack)

models$ensemble <- stack

save(models, file = "./RData/result_abs_models.RData")

model_preds <- lapply(models, predict, newdata = dat.test, interval = "prediction",level = 0.95) %>% 
  lapply(function(x) postResample(pred = x, obs = dat.test$F72)[2]) %>% 
  as.data.frame() %>%
  t() %>%
  magrittr::set_colnames("R2") %>%
  as.data.frame() %>%
  rownames_to_column("method")

model_preds$method <- factor(model_preds$method, levels = model_preds$method)

```

# validation

```{r}
# global options
rm(list = ls())
options(stringsAsFactors = FALSE)

# load data
counts <- read.table("./rawData/GSE57896/GSE57896_adipose_browning_counts.txt.gz", 
                      sep = '\t', quote = "", dec = ",", fill = T, header = T, encoding='UTF-8')

# remove duplicated genes
IDs <- bitr(counts$EntrezGeneID, fromType = "ENTREZID", toType = "SYMBOL", OrgDb = "org.Hs.eg.db")

dim(counts)
counts <- counts[counts$EntrezGeneID %in% IDs$ENTREZID,]
dim(counts)
IDs <- IDs[match(counts$EntrezGeneID,IDs$ENTREZID), ]
rownames(counts) <- IDs$SYMBOL
counts <- counts[,-1]
counts <- as.matrix(counts)

# download smaple annotation informations
getPhenoData <- function(GSE){
  require(GEOquery)
  require(tidyverse)
  getGEOfile(GSE, destdir = ".")
  eset <- getGEO(filename = paste0(GSE, ".soft.gz"))
  eset <- eset@gsms
  
  file.remove(paste0(GSE, ".soft.gz"))
  
  phenoData <- data.frame()
  
  for (i in 1:length(eset)) {
    gsm <- eset[[i]] %>% .@header 
    gsm <- c(gsm$title, gsm$characteristics_ch1)
    phenoData <- rbind(phenoData, gsm)
  }
  colnames(phenoData) <- c("sample", "type", "treatment", "time", "replicate", "batch", "lane", "multiplex")
  
  phenoData
}

phenoData <- getPhenoData(GSE = "GSE57896")

phenoData$type <- gsub("cell type: ", "", phenoData$type)
phenoData$treatment <- gsub("treatment: ", "", phenoData$treatment)
phenoData$batch <- gsub("librarybatch: ", "", phenoData$batch)

phenoData <- phenoData[phenoData$type %in% c("WAT", "BAT"),]

counts <- counts[, phenoData$sample]

group <- phenoData[,c("type", "batch")]

dds <- DESeqDataSetFromMatrix(counts, 
                              colData = group, 
                              design = ~ batch + type)


dim(dds)
cps <- fpm(dds)
keep1 <- rowSums(cps >= 1) >= ceiling(ncol(dds)*1/3)
dds <- dds[keep1, ]
dim(dds)

dds <- DESeq(dds)

# normalize counts
exprSet <- rlogTransformation(dds, blind = F) %>% assay()


# load data
load("./RData/result_abs_models.RData")
load("./RData/result_abs_background.RData")

absHBIpre <- function(exprSet, background){
  
  locAll <- c()
  for (i in names(background)) {
    bg <- c(background[[i]], i) %>% unique()
    exp <- exprSet[rownames(exprSet) %in% bg,]
    size <- nrow(exp)
    locList <- c()

    for (j in 1:ncol(exp)) {
    exprSelect <- exp[,j] %>% 
      as.data.frame() %>% 
      magrittr::set_colnames("sample") %>% 
      arrange(sample) %>% 
      rownames_to_column("symbol")
    
    geneloc <- grep(i, exprSelect$symbol)
    geneloc <- (geneloc/size)
    locList <- c(locList, geneloc)
    
    }
    locAll <- cbind(locAll, locList)%>% as.data.frame() %>% remove_rownames()
  }
  
  rownames(locAll) <- colnames(exprSet)
  colnames(locAll) <- names(background)
  
  locAll <- as.data.frame(locAll)
  
  model_preds <- predict(models[[5]], newdata = locAll)
  model_preds
}

res <- absHBIpre(exprSet = exprSet, background = genePre) %>% as.data.frame() %>% magrittr::set_colnames("fit") %>% rownames_to_column("sample")

res$label <- gsub("_TT.*", "", res$sample)
res$label <- gsub("24_hours", "24h", res$label)
res$label <- gsub("day_7", "7d", res$label)
res$label <- gsub("_DMSO.*", "", res$label)

res$cohort <- "BC3"

res_GSE57896 <- res

save(res_GSE57896, file = "./RData/result_abs_GSE57896.RData")

ggplot(res, aes(x = sample, y = fit, fill = label))+
  geom_bar(stat = 'identity', position = "dodge")

```

```{r}
# global options
rm(list = ls())
options(stringsAsFactors = FALSE)

# load data
rawData <- read.table("./rawData/GSE113764/GSE113764_humanBATWAT.txt.gz", 
                      sep = '\t', quote = "", dec = ",", fill = T, header = T, encoding='UTF-8', check.names = F)
rawData <- rawData[which(rawData$GeneId > 0),]

# filter low-expressed genes
dim(rawData)
keep <- rowSums(rawData[,4:ncol(rawData)] >=1 ) >= 15
rawData <- rawData[keep, ]
dim(rawData)

# remove duplicated genes
rpkm <- avereps(rawData[, 4:ncol(rawData)], ID = rawData$Symbol)

# trans to TPM
fpkmToTpm <- function(fpkm)
{
  exp(log(fpkm) - log(sum(fpkm)) + log(1e6))
}

tpm <- apply(rpkm, 2, fpkmToTpm)

# download smaple annotation informations
getPhenoData <- function(GSE){
  require(GEOquery)
  require(tidyverse)
  getGEOfile(GSE, destdir = ".")
  eset <- getGEO(filename = paste0(GSE, ".soft.gz"))
  eset <- eset@gsms
  
  file.remove(paste0(GSE, ".soft.gz"))
  
  phenoData <- data.frame()
  
  for (i in 1:length(eset)) {
    gsm <- eset[[i]] %>% .@header 
    gsm <- c(gsm$geo_accession, gsm$characteristics_ch1, gsm$title)
    phenoData <- rbind(phenoData, gsm)
  }
  colnames(phenoData) <- c("sample", "individual", "tissue", "group", "indiGroup")
  
  phenoData
}

phenoData <- getPhenoData(GSE = "GSE113764")
phenoData$tissue <- gsub("tissue: ", "", phenoData$tissue)
phenoData$group <- gsub("18fdg-pet-ct: BAT ", "", phenoData$group)
phenoData$iden <- phenoData$tissue

colnames(tpm) <- gsub("P\xe4o", "Pao", colnames(tpm))
tpm <- tpm[, phenoData$indiGroup]

#load data
load("./RData/result_abs_models.RData")
load("./RData/result_abs_background.RData")

absHBIpre <- function(exprSet, background){
  
  locAll <- c()
  for (i in names(background)) {
    bg <- c(background[[i]], i) %>% unique()
    exp <- exprSet[rownames(exprSet) %in% bg,]
    size <- nrow(exp)
    locList <- c()

    for (j in 1:ncol(exp)) {
    exprSelect <- exp[,j] %>% 
      as.data.frame() %>% 
      magrittr::set_colnames("sample") %>% 
      arrange(sample) %>% 
      rownames_to_column("symbol")
    
    geneloc <- grep(i, exprSelect$symbol)
    geneloc <- (geneloc/size)
    locList <- c(locList, geneloc)
    
    }
    locAll <- cbind(locAll, locList)%>% as.data.frame() %>% remove_rownames()
  }
  
  rownames(locAll) <- colnames(exprSet)
  colnames(locAll) <- names(background)
  
  locAll <- as.data.frame(locAll)
  
  model_preds <- predict(models[[5]], newdata = locAll)
  model_preds
}

res <- absHBIpre(tpm, background = genePre) %>% as.data.frame() %>% magrittr::set_colnames("fit") %>% rownames_to_column("sample")

res$label <- phenoData$iden
res$cohort <- "BT1"

res_GSE113764 <- res

save(res_GSE113764, file = "./RData/result_abs_GSE113764.RData")

ggplot(res, aes(x = sample, y = fit, fill = label))+
  geom_bar(stat = 'identity', position = "dodge")

```

```{r}
# global options
rm(list = ls())
options(stringsAsFactors = FALSE)

# load data
readRawCounts <- function(path){
  require(stringr)
  
  file <- list.files(path = path, pattern = "\\.txt.gz$", full.names = T)
  
  file.short <- list.files(path = path, pattern = "\\.txt.gz$", full.names = F)
  name <- str_split(file.short, pattern = "_", simplify = T)[,1]

  
  pb <- txtProgressBar(0, length(file), style = 3)
  for (i in 1:length(file)) {
    a <- file[i]
    rawCounts <- read.table(file = a, sep = '\t', quote = "", fill = T)
    colnames(rawCounts) <- c("geneID", name[i])
    if(i > 1) {
      counts <- merge(counts, rawCounts, by = "geneID") 
    } else {
      counts <- rawCounts
    }
    setTxtProgressBar(pb, i)
  }
  close(pb)

  rownames(counts) <- counts$geneID
  
  counts <- counts[,-1]
  counts <- apply(counts, c(1,2), as.numeric)
  counts
}

counts <- readRawCounts(path = "./rawData/GSE125331")

# get sample annotation informations
file.short <- list.files(path = "./rawData/GSE125331", pattern = "\\.txt.gz$", full.names = F)

phenoData <- str_split(file.short, pattern = "_", simplify = T)[,1:2] %>% magrittr::set_colnames(c("sample", "group")) %>% as.data.frame()

phenoData <- phenoData[phenoData$group %in% c("Beige", "White"), ]
phenoData$group <- ifelse(phenoData$group == "Beige", "BAT", "WAT")

# isolate counts
counts <- counts[, phenoData$sample]

# run DESeq2
colData <- phenoData[,c("sample","group")]

dds <- DESeqDataSetFromMatrix(counts, 
                              colData = colData, 
                              design = ~ group)
# filter low-expressed genes
dim(dds)
cps <- fpm(dds)
keep1 <- rowSums(cps >= 1) >= ceiling(ncol(dds)*3/4)
dds <- dds[keep1, ]
dim(dds)

# call DESeq function
dds <- DESeq(dds)

# normalize counts
exprSet <- rlogTransformation(dds, blind = T) %>% assay()

#load data
load("./RData/result_abs_models.RData")
load("./RData/result_abs_background.RData")

absHBIpre <- function(exprSet, background){
  
  locAll <- c()
  for (i in names(background)) {
    bg <- c(background[[i]], i) %>% unique()
    exp <- exprSet[rownames(exprSet) %in% bg,]
    size <- nrow(exp)
    locList <- c()

    for (j in 1:ncol(exp)) {
    exprSelect <- exp[,j] %>% 
      as.data.frame() %>% 
      magrittr::set_colnames("sample") %>% 
      arrange(sample) %>% 
      rownames_to_column("symbol")
    
    geneloc <- grep(i, exprSelect$symbol)
    geneloc <- (geneloc/size)
    locList <- c(locList, geneloc)
    
    }
    locAll <- cbind(locAll, locList)%>% as.data.frame() %>% remove_rownames()
  }
  
  rownames(locAll) <- colnames(exprSet)
  colnames(locAll) <- names(background)
  
  locAll <- as.data.frame(locAll)
  
  model_preds <- predict(models[[5]], newdata = locAll)
  model_preds
}

res <- absHBIpre(exprSet, background = genePre) %>% as.data.frame() %>% magrittr::set_colnames("fit") %>% rownames_to_column("sample")

res$label <- phenoData$group
res$cohort <- "BC4"

res_GSE125331 <- res

save(res_GSE125331, file = "./RData/result_abs_GSE125331.RData")

ggplot(res, aes(x = sample, y = fit, fill = label))+
  geom_bar(stat = 'identity', position = "dodge")

```


```{r}
# global options
rm(list = ls())
options(stringsAsFactors = FALSE)

load("./RData/result_abs_GSE57896.RData")
load("./RData/result_abs_GSE113764.RData")
load("./RData/result_abs_GSE125331.RData")

res <- Reduce(rbind, list(res_GSE57896, res_GSE113764, res_GSE125331)) %>% 
  arrange(fit) %>%
  mutate(sample = factor(sample, levels = sample)) %>%
  mutate(Group = gsub("_.*", "_pertb", label))

p <- ggplot(res, aes(x = sample, y = fit, fill = Group))+
  geom_bar(stat = 'identity', position = "dodge")+
  scale_fill_manual(values = c("#0095C4", "#B44946", "#DB802D"))+
  xlab("Sample")+ylab("Absolute HBI")+
  theme_classic()+
  theme(axis.text.x = element_blank(),
        axis.line.x = element_line(size = 0.3),
        axis.line.y = element_line(size = 0.3),
        axis.ticks.x = element_line(size = 0.3),
        axis.ticks.y = element_line(size = 0.3))

pdf(file = "./plot/abs_HBI.pdf", width = 7, height = 4)
p
dev.off()

```

# T2D cohort

```{r}
# global options
rm(list = ls())

# load data
load("./RData/cohort_GSE135134.RData")
load("./RData/result_matsuda.RData")
load("./RData/result_abs_models.RData")
load("./RData/result_abs_background.RData")

# merge data
phenoData <- phenoData[phenoData$sample %in% phenoData.matsuda$sample,]
phenoData$matsuda <- phenoData.matsuda$matsuda[match(phenoData$sample, phenoData.matsuda$sample)]
phenoData$group3 <- ifelse(phenoData$matsuda >= 4.3, "IS", "IR")
phenoData <- phenoData[phenoData$group3 == "IR",]
ltpms <- ltpms[,phenoData$sample]

absHBIpre <- function(exprSet, background){
  
  locAll <- c()
  for (i in names(background)) {
    bg <- c(background[[i]], i) %>% unique()
    exp <- exprSet[rownames(exprSet) %in% bg,]
    size <- nrow(exp)
    locList <- c()

    for (j in 1:ncol(exp)) {
    exprSelect <- exp[,j] %>% 
      as.data.frame() %>% 
      magrittr::set_colnames("sample") %>% 
      arrange(sample) %>% 
      rownames_to_column("symbol")
    
    geneloc <- grep(i, exprSelect$symbol)
    geneloc <- (geneloc/size)
    locList <- c(locList, geneloc)
    
    }
    locAll <- cbind(locAll, locList)%>% as.data.frame() %>% remove_rownames()
  }
  
  rownames(locAll) <- colnames(exprSet)
  colnames(locAll) <- names(background)
  
  locAll <- as.data.frame(locAll)
  
  model_preds <- predict(models[[5]], newdata = locAll)
  model_preds
}

res <- absHBIpre(ltpms, background = genePre) %>% as.data.frame() %>% magrittr::set_colnames("fit")

# gene correlation
cor.gene <- function(dat1, dat2){
  res.cor <- apply(dat2, 1, function(x) cor.test(dat1, x))
  
  res.cor <- sapply(res.cor, function(x) c(x$estimate, x$p.value), simplify = T) %>% t() %>% as.data.frame() %>% magrittr::set_colnames(c("Coefficient", "p"))
  
  res.cor$p <- -log10(res.cor$p)
  res.cor$name <- rownames(res.cor)
  
  res.cor
}

res.cor <- cor.gene(dat1 = res$fit, dat2 = ltpms) %>% na.omit()

p1 <- ggplot(res.cor, aes(x = Coefficient, y = p, color = Coefficient))+
  geom_point()+
  scale_color_paletteer_c("ggthemes::Classic Red-Blue", direction = -1, limits = c(-1, 1))+
  labs(x = " ",y = "-log10(P Value)", title = "Gene correlations (IR)")+
  geom_label_repel( 
    data = res.cor[res.cor$name %in% c("PPARG", "CEBPA", "ACADL", "ADIPOQ", "CPT2", "ACSL1", "COX5A ", "ACSL3"),], 
    aes(label = name)
  )+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))

n=table(res.cor$Coefficient >= 0.8)[2]
goList.cor <- res.cor %>% arrange(desc(Coefficient)) %>% head(n) %>% magrittr::use_series("name")

go.cor <- enrichGO(goList.cor, 
               OrgDb = "org.Hs.eg.db", 
               ont = 'BP',
               pAdjustMethod = 'BH',
               pvalueCutoff = 0.05, 
               qvalueCutoff = 0.99,
               keyType = "SYMBOL")

# 20220619
categorys <- c("response to insulin", "cellular response to insulin stimulus", "regulation of cellular response to insulin stimulus", "positive regulation of glucose import", "regulation of glucose import", "regulation of glucose transmembrane transport", "glucose import")

p2 <- dotplot(go.cor, title = "Insulin resistance", showCategory = categorys, label_format = 99999)+
  scale_fill_paletteer_c("ggthemes::Classic Red-Blue", direction = -1, trans = "reverse")+
  theme(plot.title = element_text(hjust = 0.5))

pdf(file = "./plot/abs_HBI_corIR.pdf", width = 14, height = 5)
p1+p2
dev.off()

```






